name: Pre-Commit

on:
  workflow_call:
  pull_request_target:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      # Check out the appropriate branch
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request_target'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
        env:
          COMMIT_MESSAGE: "Run pre-commit"
      - uses: actions/checkout@v3
        if: github.event_name != 'pull_request_target'
        env:
          COMMIT_MESSAGE: "Run pre-commit"

      # Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "**/requirements*.txt"

      # Run pre-commit
      - uses: pre-commit/action@v3.0.0

      # Post PR comment on failure
      - name: Post PR comment on failure
        if: failure() && github.event_name == 'pull_request_target'
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            :x: **pre-commit** failed.
            Please run `pre-commit run --all-files` locally and commit the changes.
            Find more information in the repository's CONTRIBUTING.md
