name: E2E Tests (Website)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start services
        run: docker compose --profile ci up --build -d
      - name: Run e2e tests
        uses: cypress-io/github-action@v5.0.2
        with:
          browser: chrome
          working-directory: website
      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: website/cypress/screenshots
      - name: cypress-videos
        path: website/cypress/videos
      - name: Send notification
        uses: actions/send-notification@v3
        with:
          recipients:
            - my-email@example.com
          subject: E2E Tests Failed
          body: 'E2E tests failed. Check the screenshots and videos in the artifacts.'
          icons:
            - google-chrome
